#!/bin/bash

if [[ ${OSTYPE:0:6} == darwin* ]]; then
    dir=$(dirname $0)
    path=$PWD${dir:1}
else
    path=$(dirname $(readlink -f $0))
fi

ln -s "$path"/.gitconfig ~/.gitconfig
ln -s "$path"/.gitignore ~/.gitignore

if [ -d ~/.bash_plugins ]; then
    cd ~/.bash_plugins
    wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
fi
