#!/bin/bash

if [[ ${OSTYPE:0:6} == "darwin" ]]; then
    dir=$(dirname $0)
    path=$PWD${dir:1}
else
    path=$(dirname $(readlink -f $0))
fi

ln -s "$path"/.gitconfig ~/.gitconfig
ln -s "$path"/.gitignore ~/.gitignore
